//HintName: ITest.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests
{
    public partial interface IClass1
    {
        string? GeneratedProperty { get; set; }
    }
}