//HintName: ITest.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests
{
    public partial interface IClass1
    {
        string Private1 { get; }

        string Protected1 { get; }

        string File1 { get; }

        string Internal1 { get; }

        string Private2 { get; }

        string Protected2 { get; }

        string File2 { get; }

        string Internal2 { get; }
    }
}