//HintName: GenerateInterfaceAttribute.g.cs
// <auto-generated/>
namespace MakeInterface;

internal sealed class GenerateInterfaceAttribute : System.Attribute
{
    public string[]? Exclude { get; set; }
}