//HintName: ITest.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests
{
    public partial interface IMyBase
    {
        string Name { get; set; }
    }

    public partial interface IMySub : IMyBase
    {
        int Number { get; set; }
    }
}