//HintName: ITest.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using NewName = MakeInterface.Tests.Models.NamedModel;

namespace MakeInterface.Tests
{
    public partial interface IClass1
    {
        NewName GetNewName { get; }

        NewName SetNewName(NewName name);
    }
}

namespace MakeInterface.Tests.Models
{
}