//HintName: ITest.g.cs
using NewName = MakeInterface.Tests.Models.NamedModel;

// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests
{
    public partial interface IClass1
    {
        public NewName GetNewName { get; }

        NewName SetNewName(NewName name);
    }
}

// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests.Models
{
}