//HintName: ITest.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
using System.Threading;
using System.Threading.Tasks;

namespace MakeInterface.Tests
{
    public partial interface IViewModel
    {
        // This property was generated because of the RelayCommand attribute applied to the 'DoStuff' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand DoStuffCommand { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'DoStuffWithParam' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand<string> DoStuffWithParamCommand { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'DoStuffWithSystemThreadingCancellationToken' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand DoStuffWithSystemThreadingCancellationTokenCommand { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'DoStuffWithGlobalCancellationToken' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand DoStuffWithGlobalCancellationTokenCommand { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'SyncWithCancellationToken' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IRelayCommand SyncWithCancellationTokenCommand { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'SyncWithParamAndCancellationToken' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IRelayCommand<string> SyncWithParamAndCancellationTokenCommand { get; }
    }
}
