//HintName: ITest.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests
{
    public partial interface IClass1 : System.IDisposable, IGeneric<string>
    {
    }

    public partial interface IClass2
    {
    }
}