//HintName: ITestModel.g.cs
#nullable enable
using MakeInterface.Tests.Models;
using MakeInterface.Contracts.Attributes;
using System.Collections.Generic;

// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests.Models;
public partial interface ITestModel
{
}