//HintName: ITest.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests
{
    public partial interface IClass1
    {
        // This property was generated because of the RelayCommand attribute applied to the 'Test' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IRelayCommand TestCommand { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test2' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IRelayCommand Test2Command { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test3' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand Test3Command { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test3_1Async' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand Test3_1Command { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test4' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand Test4Command { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test5' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand Test5Command { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test6' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand Test6Command { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test7' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IRelayCommand<string> Test7Command { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test8' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand Test8Command { get; }

        // This property was generated because of the RelayCommand attribute applied to the 'Test9' method. See https://aka.ms/CommunityToolkit.MVVM
        global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand Test9Command { get; }
    }
}