//HintName: MakeInterface.InterfaceIncludeAttribute.g.cs
// <auto-generated/>
#nullable enable
namespace MakeInterface
{
    /// <summary>Marks a member that should be included in the generated interface.</summary>
    [System.AttributeUsage(
        System.AttributeTargets.Method |
        System.AttributeTargets.Property |
        System.AttributeTargets.Event)]
    internal sealed class InterfaceIncludeAttribute : System.Attribute { }
}