//HintName: ITest.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests
{
    public partial interface IClass1
    {
        public string Private1 { get; }

        public string Protected1 { get; }

        public string File1 { get; }

        public string Internal1 { get; }

        public string Private2 { get; }

        public string Protected2 { get; }

        public string File2 { get; }

        public string Internal2 { get; }
    }
}