//HintName: IClass1.g.cs
using NewName = MakeInterface.Tests.Models.NamedModel;

// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MakeInterface.Tests;
public partial interface IClass1
{
    NewName GetNewName { get; }

    ;
    NewName SetNewName(NewName name);
}