using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using VerifyCS = MakeInterface.Tests.CSharpSourceGeneratorVerifier<MakeInterface.Generator.InterfaceGenerator>;
using Microsoft.CodeAnalysis.Testing;
using MakeInterface.Generator;

namespace MakeInterface.Tests;

public class InterfaceGeneratorTests
{
    private static readonly string _header = """
        // <auto-generated/>
        #pragma warning disable
        #nullable enable
        namespace MakeInterface.Tests;
        
        """;

    private readonly ImmutableArray<string> references = AppDomain.CurrentDomain
    .GetAssemblies()
    .Where(assembly => !assembly.IsDynamic)
    .Select(assembly => assembly.Location)
    .ToImmutableArray();
    
    private async Task RunTestAsync(string code, string expectedResult)
    {
        var tester = new VerifyCS.Test
        {
            TestState =
                {
                    Sources = { code },
                    GeneratedSources =
                    {
                        (typeof(InterfaceGenerator), "IClass1.g.cs",
                            SourceText.From(expectedResult, Encoding.UTF8))
                    }
                },
            ReferenceAssemblies = ReferenceAssemblies.Net.Net60
        };

        tester.ReferenceAssemblies.AddAssemblies(references);
        tester.TestState.AdditionalReferences.Add(typeof(InterfaceGenerator).Assembly);
        tester.TestState.AdditionalReferences.Add(typeof(Contracts.Attributes.GenerateInterfaceAttribute).Assembly);

        await tester.RunAsync();
    }

    [Fact]
    public async Task CreateInterface()
    {
        var code = """
using MakeInterface.Tests.Models;
using MakeInterface.Contracts.Attributes;
namespace MakeInterface.Tests
{
    [GenerateInterface]
    public class Class1
    {
        public void Method1() { }
        public TestModel Test() { return new TestModel(); }
        public void Test2<T>(T data) { }
        public void Test3<T>(T data) where T : TestModel { }
        public string Property1 { get; set; }
    }
}

namespace MakeInterface.Tests.Models
{
    public class TestModel
    {
        
    }
}
""";

        var expected = _header + """
public interface IClass1
{
    void Method1();
    MakeInterface.Tests.Models.TestModel Test();
    void Test2<T>(T data);
    void Test3<T>(T data)
        where T : MakeInterface.Tests.Models.TestModel;
    string Property1 { get; set; }
}
""";


        await RunTestAsync(code, expected);
        Assert.True(true); // silence warnings, real test happens in the RunAsync() method
    }
}